---
  - name: Install and Configure Metricbeat
    hosts: elkservers
    become: yes
    tasks:

    - name: download metricbeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: install metricbeat deb
      command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

    - name: copy filebeat config yml to webservers
      copy:
        src: /etc/ansible/files/metricbeat-configuration.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: enable and configure docker module
      command: sudo metricbeat modules enable docker

    - name: set up metricbeat
      command: sudo metricbeat setup

    - name: start metricbeat
      command: sudo service metricbeat start